package db

import (
	"context"
	"database/sql"
	"fmt"
	"log"
	"math/rand"

	"github.com/AmiyoKm/go-backend/internal/store"
)

var userNames = []string{
	"Alice",
	"Bob",
	"Charlie",
	"David",
	"Eve",
	"Frank",
	"Grace",
	"Heidi",
	"Ivan",
	"Judy",
	"Kevin",
	"Liam",
	"Mia",
	"Noah",
	"Olivia",
	"Peter",
	"Quinn",
	"Ruby",
	"Sophia",
	"Thomas",
	"Uma",
	"Victor",
	"Wendy",
	"Xavier",
	"Yara",
	"Zoe",
	"Adam",
	"Bella",
	"Caleb",
	"Diana",
	"Ethan",
	"Fiona",
	"George",
	"Hannah",
	"Isaac",
	"Jade",
	"Kyle",
	"Luna",
	"Mason",
	"Nora",
	"Owen",
	"Piper",
	"Ryan",
	"Stella",
	"Tyler",
	"Violet",
	"Wyatt",
	"Xena",
	"Yusuf",
	"Zara",
}

var titles = []string{
	"The Art of Programming",
	"Exploring the Cosmos",
	"A Journey Through History",
	"The Science of Cooking",
	"Understanding Artificial Intelligence",
	"The Beauty of Nature",
	"Mastering Data Structures",
	"The World of Finance",
	"Introduction to Quantum Physics",
	"The Secrets of the Ocean",
	"Learning a New Language",
	"The Power of Meditation",
	"Adventures in Hiking",
	"The History of Music",
	"Creative Writing Techniques",
	"Exploring Ancient Civilizations",
	"The Future of Technology",
	"Understanding Climate Change",
	"The Basics of Photography",
	"The Philosophy of Mind",
	"Gardening for Beginners",
	"The World of Mythology",
	"Introduction to Machine Learning",
	"The Art of Negotiation",
	"Exploring Different Cultures",
	"The Science of Sleep",
	"Mastering Algorithms",
	"The History of Art",
	"The Basics of Economics",
	"Understanding Blockchain",
	"The Joy of Painting",
	"The World of Literature",
	"Introduction to Neuroscience",
	"The Art of Public Speaking",
	"Exploring National Parks",
	"The Science of Happiness",
	"Mastering Web Development",
	"The History of Film",
	"The Basics of Investing",
	"Understanding Cybersecurity",
	"The Magic of Theater",
	"The World of Poetry",
	"Introduction to Psychology",
	"The Art of Storytelling",
	"Exploring World Religions",
	"The Science of Nutrition",
	"Mastering Graphic Design",
	"The History of Architecture",
	"The Basics of Marketing",
	"Understanding Cloud Computing",
	"The Thrill of Travel",
	"The World of Philosophy",
	"Introduction to Sociology",
	"The Art of Calligraphy",
	"Exploring Space Exploration",
	"The Science of Genetics",
	"Mastering Mobile App Development",
	"The History of Photography",
	"The Basics of Accounting",
	"Understanding Data Science",
	"The Beauty of Mathematics",
	"The World of Comics",
	"Introduction to Anthropology",
	"The Art of Sculpture",
	"Exploring Underwater Worlds",
	"The Science of Aging",
	"Mastering Game Development",
	"The History of Dance",
	"The Basics of Entrepreneurship",
	"Understanding Virtual Reality",
	"The Adventure of Sailing",
	"The World of Drama",
	"Introduction to Linguistics",
	"The Art of Pottery",
	"Exploring Urban Landscapes",
	"The Science of Sound",
	"Mastering Digital Marketing",
	"The History of Fashion",
	"The Basics of Real Estate",
	"Understanding Augmented Reality",
	"The Excitement of Skiing",
	"The World of Opera",
	"Introduction to Archaeology",
	"The Art of Origami",
	"Exploring Desert Ecosystems",
	"The Science of Light",
	"Mastering UI/UX Design",
	"The History of Television",
	"The Basics of Project Management",
	"Understanding Big Data",
	"The Serenity of Yoga",
	"The World of Musicals",
	"Introduction to Criminology",
	"The Art of Woodworking",
	"Exploring Mountain Ranges",
	"The Science of Taste",
	"Mastering Cloud Architecture",
	"The History of Radio",
	"The Basics of Human Resources",
	"Understanding Internet of Things",
	"The Challenge of Rock Climbing",
	"The World of Ballet",
	"Introduction to Political Science",
	"The Art of Glassblowing",
	"Exploring Rainforests",
	"The Science of Smell",
	"Mastering DevOps",
	"The History of Video Games",
	"The Basics of Supply Chain Management",
	"Understanding Natural Language Processing",
	"The Fun of Cycling",
	"The World of Jazz",
	"Introduction to Geology",
	"The Art of Knitting",
	"Exploring Arctic Regions",
	"The Science of Touch",
	"Mastering Cybersecurity Fundamentals",
	"The History of the Internet",
	"The Basics of Public Relations",
	"Understanding Robotics",
	"The Peace of Fishing",
	"The World of Classical Music",
	"Introduction to Astronomy",
	"The Art of Sewing",
	"Exploring Coral Reefs",
	"The Science of Memory",
	"Mastering Network Engineering",
	"The History of Printing",
	"The Basics of Logistics",
	"Understanding Computer Vision",
	"The Joy of Running",
	"The World of Folk Music",
	"Introduction to Meteorology",
	"The Art of Jewelry Making",
	"Exploring Savannas",
	"The Science of Emotion",
	"Mastering Database Administration",
	"The History of Transportation",
	"The Basics of Operations Management",
	"Understanding Quantum Computing",
	"The Thrill of Surfing",
	"The World of Blues Music",
	"Introduction to Oceanography",
	"The Art of Bookbinding",
	"Exploring Wetlands",
	"The Science of Learning",
	"Mastering System Administration",
	"The History of Medicine",
	"The Basics of Financial Planning",
	"Understanding Bioinformatics",
	"The Relaxation of Swimming",
	"The World of Rock Music",
	"Introduction to Botany",
	"The Art of Calligraphy Revisited",
	"Exploring Grasslands",
	"The Science of Motivation",
	"Mastering Software Testing",
	"The History of Agriculture",
	"The Basics of E-commerce",
	"Understanding Geographic Information Systems",
	"The Excitement of Skateboarding",
	"The World of Pop Music",
	"Introduction to Zoology",
	"The Art of Mosaics",
	"Exploring Tundra",
	"The Science of Perception",
	"Mastering Embedded Systems",
	"The History of Education",
	"The Basics of Business Strategy",
	"Understanding Cryptography",
	"The Adventure of Kayaking",
	"The World of Hip Hop Music",
	"Introduction to Ecology",
	"The Art of Stained Glass",
	"Exploring Caves",
	"The Science of Decision Making",
	"Mastering Artificial Intelligence Ethics",
	"The History of Law",
	"The Basics of International Business",
	"Understanding Recommender Systems",
	"The Fun of Camping",
	"The World of Country Music",
	"Introduction to Paleontology",
	"The Art of Weaving",
	"Exploring Volcanoes",
	"The Science of Consciousness",
	"Mastering Quantum Algorithms",
	"Advanced Go Programming",
	"Building Scalable Systems",
	"Microservices Architecture",
	"Distributed Systems Design",
	"Cloud Native Go",
	"Concurrency Patterns in Go",
	"Go for Data Science",
	"Web Development with Go",
	"API Design in Go",
	"Testing Go Applications",
}
var content = []string{
	"Dive deep into the fundamentals and advanced concepts of software development.",
	"Embark on a celestial voyage, discovering planets, stars, and galaxies.",
	"Uncover the pivotal moments and figures that shaped our world.",
	"Learn the chemical reactions and techniques behind delicious meals.",
	"Explore the algorithms and theories driving intelligent machines.",
	"Appreciate the intricate beauty of landscapes, flora, and fauna.",
	"Grasp essential data organization techniques for efficient programming.",
	"Navigate the complex world of investments, markets, and economics.",
	"Delve into the strange and fascinating principles of subatomic particles.",
	"Discover the mysteries hidden beneath the waves, from trenches to reefs.",
	"Master the grammar, vocabulary, and culture of a foreign tongue.",
	"Find inner peace and focus through mindfulness and meditation practices.",
	"Experience the thrill and serenity of exploring trails and mountains.",
	"Trace the evolution of musical styles, instruments, and composers.",
	"Unlock your imagination and craft compelling narratives and stories.",
	"Journey back in time to explore the rise and fall of great empires.",
	"Peek into the innovations and trends shaping our technological future.",
	"Understand the causes, impacts, and solutions for global warming.",
	"Capture stunning images by learning composition, lighting, and settings.",
	"Contemplate the nature of thought, consciousness, and existence.",
	"Cultivate your own green space, learning planting and care techniques.",
	"Explore the ancient myths and legends that explain the world.",
	"Understand the core concepts of algorithms that learn from data.",
	"Develop the skills to persuade, influence, and reach agreements.",
	"Broaden your horizons by learning about diverse global traditions.",
	"Unravel the science behind restful sleep and its importance for health.",
	"Solve complex problems efficiently with advanced algorithm design.",
	"Appreciate the masterpieces and movements throughout art history.",
	"Learn the principles of supply, demand, and market forces.",
	"Demystify the distributed ledger technology behind cryptocurrencies.",
	"Express your creativity on canvas with colors, brushes, and techniques.",
	"Immerse yourself in the world of novels, poetry, and classic texts.",
	"Explore the structure and function of the brain and nervous system.",
	"Gain confidence and skill in delivering impactful presentations.",
	"Discover the natural beauty and wonders preserved in national parks.",
	"Learn the psychological and physiological factors contributing to well-being.",
	"Build dynamic and interactive websites using modern frameworks.",
	"Explore the history of cinema, from silent films to blockbusters.",
	"Understand the basics of stocks, bonds, and building wealth.",
	"Learn how to protect digital information from threats and attacks.",
	"Experience the magic of live performance, acting, and stagecraft.",
	"Delve into the expressive power of verse, meter, and poetic form.",
	"Understand human behavior, cognition, and emotional processes.",
	"Master the craft of weaving engaging plots and characters.",
	"Examine the beliefs, practices, and histories of major world faiths.",
	"Learn about macronutrients, vitamins, and healthy eating habits.",
	"Create visually appealing designs for print and digital media.",
	"Trace the evolution of building styles and structural innovations.",
	"Learn strategies for promoting products and reaching customers.",
	"Understand the infrastructure and services powering the internet.",
	"Embark on exciting journeys to explore new places and cultures.",
	"Engage with fundamental questions about reality, knowledge, and ethics.",
	"Study the structures, interactions, and dynamics of human societies.",
	"Master the elegant art of beautiful handwriting and lettering.",
	"Learn about the challenges and triumphs of venturing into space.",
	"Explore the code of life: DNA, heredity, and genetic engineering.",
	"Develop applications for smartphones and tablets on various platforms.",
	"Trace the evolution of capturing images, from daguerreotypes to digital.",
	"Understand the principles of financial recording, reporting, and analysis.",
	"Learn techniques to extract insights and knowledge from data.",
	"Appreciate the elegance and power of numbers, logic, and proofs.",
	"Explore the vibrant world of graphic novels and sequential art.",
	"Study human origins, cultures, and social structures across time.",
	"Create three-dimensional works of art using various materials.",
	"Discover the unique ecosystems and life forms beneath the water.",
	"Understand the biological processes of growing older.",
	"Learn the principles of designing and developing video games.",
	"Explore the history and evolution of various dance forms.",
	"Gain the knowledge and skills to start and manage a business.",
	"Immerse yourself in computer-generated environments and experiences.",
	"Learn the techniques and joys of navigating waters by sailboat.",
	"Explore the world of plays, scripts, and theatrical performance.",
	"Study the structure, evolution, and use of human language.",
	"Shape clay into functional and artistic ceramic creations.",
	"Discover the unique characteristics and challenges of city environments.",
	"Understand the physics of sound waves, acoustics, and music.",
	"Learn strategies for online marketing, SEO, and social media.",
	"Trace the changing trends and influences in clothing and style.",
	"Understand the principles of buying, selling, and managing property.",
	"Explore technology that overlays digital information onto the real world.",
	"Experience the exhilaration of gliding down snow-covered slopes.",
	"Discover the dramatic and musical world of operatic performances.",
	"Unearth the past through the study of artifacts and ancient sites.",
	"Master the delicate art of paper folding to create intricate shapes.",
	"Learn about the unique flora, fauna, and climate of arid regions.",
	"Understand the physics of light, optics, and visual phenomena.",
	"Design intuitive and engaging interfaces for websites and apps.",
	"Trace the history of broadcasting, from early shows to streaming.",
	"Learn methodologies for planning, executing, and closing projects.",
	"Understand how to process and analyze massive datasets.",
	"Find balance and flexibility through ancient postures and breathing.",
	"Explore the world of stage productions combining song, dance, and story.",
	"Study the nature, causes, and consequences of criminal behavior.",
	"Craft objects and furniture using traditional woodworking techniques.",
	"Explore the geology, ecology, and beauty of high-altitude terrains.",
	"Understand the chemical senses responsible for flavor perception.",
	"Design and manage scalable and resilient cloud infrastructure.",
	"Trace the history of audio broadcasting and its cultural impact.",
	"Learn principles of managing employees, recruitment, and relations.",
	"Understand the network of physical devices embedded with sensors.",
	"Experience the physical and mental challenge of ascending rock faces.",
	"Explore the grace and discipline of classical ballet performance.",
	"Study systems of government, political behavior, and theory.",
	"Shape molten glass into beautiful and intricate art forms.",
	"Discover the biodiversity and ecological importance of rainforests.",
	"Understand the chemical senses responsible for detecting odors.",
	"Master practices for automating software development and deployment.",
	"Trace the evolution of interactive entertainment from arcades to consoles.",
	"Learn principles of managing the flow of goods and services.",
	"Understand how computers interpret and process human language.",
	"Enjoy the physical and mental benefits of riding a bicycle.",
	"Explore the improvisational and syncopated world of jazz music.",
	"Study the Earth's physical structure, substances, and history.",
	"Create textiles and crafts using yarn and needles.",
	"Learn about the unique ecosystems and challenges of polar regions.",
	"Understand the sensory system responsible for physical sensation.",
	"Grasp the essential concepts of protecting computer systems.",
	"Trace the development of the global network connecting computers.",
	"Learn strategies for managing communication and public image.",
	"Understand the design, construction, and operation of robots.",
	"Find tranquility and patience by the water, waiting for a catch.",
	"Explore the rich history and structure of orchestral music.",
	"Study celestial objects, space, and the physical universe.",
	"Craft garments and items using fabric, thread, and needles.",
	"Discover the vibrant and fragile ecosystems of coral reefs.",
	"Understand how the brain encodes, stores, and retrieves information.",
	"Design, implement, and manage computer networks effectively.",
	"Trace the history of reproducing text and images.",
	"Learn principles of coordinating storage and transportation of goods.",
	"Understand how computers 'see' and interpret visual information.",
	"Experience the cardiovascular and mental benefits of running.",
	"Explore the traditions and storytelling in folk music genres.",
	"Study the Earth's atmosphere and weather patterns.",
	"Design and create intricate adornments using metals and gems.",
	"Learn about the unique ecosystems of grassy plains.",
	"Understand the psychological forces driving human feelings.",
	"Manage and maintain database systems for optimal performance.",
	"Trace the evolution of methods for moving people and goods.",
	"Learn principles of overseeing production and service delivery.",
	"Explore the counter-intuitive world of quantum computation.",
	"Experience the excitement of riding waves on a surfboard.",
	"Explore the history and soulful expression of blues music.",
	"Study the physical and biological aspects of the oceans.",
	"Master the craft of assembling and binding books by hand.",
	"Discover the unique ecosystems found in waterlogged lands.",
	"Understand the cognitive processes involved in acquiring knowledge.",
	"Install, configure, and maintain operating systems and servers.",
	"Trace the development of healing practices and medical knowledge.",
	"Learn strategies for managing personal finances and investments.",
	"Understand computational approaches to biological data analysis.",
	"Enjoy the low-impact exercise and relaxation of swimming.",
	"Explore the energy, history, and subgenres of rock music.",
	"Study the science of plant life, structure, and classification.",
	"Revisit the elegant art of beautiful handwriting and lettering.",
	"Learn about the ecosystems dominated by grasses and sparse trees.",
	"Understand the psychological processes that initiate and direct behavior.",
	"Ensure software quality through systematic testing procedures.",
	"Trace the development of farming techniques and food production.",
	"Learn principles of conducting business transactions online.",
	"Understand systems for capturing and analyzing spatial data.",
	"Experience the urban sport of riding and performing tricks on a skateboard.",
	"Explore the catchy tunes and cultural impact of popular music.",
	"Study the science of animal life, behavior, and classification.",
	"Create intricate images using small pieces of colored material.",
	"Learn about the cold, treeless regions with permafrost.",
	"Understand how sensory information is organized and interpreted.",
	"Design and program systems embedded within larger devices.",
	"Trace the history of teaching methods and educational institutions.",
	"Learn frameworks for developing long-term organizational goals.",
	"Understand techniques for secure communication and data protection.",
	"Experience the adventure of paddling through rivers and lakes.",
	"Explore the rhythmic and lyrical world of hip hop culture.",
	"Study the interactions between organisms and their environment.",
	"Create colorful designs by assembling pieces of colored glass.",
	"Discover the hidden worlds within underground cave systems.",
	"Understand the cognitive processes involved in making choices.",
	"Explore the ethical considerations surrounding intelligent systems.",
	"Trace the development of legal systems and principles.",
	"Learn strategies for conducting business across national borders.",
	"Understand algorithms that predict user preferences.",
	"Enjoy the simplicity and connection with nature while camping.",
	"Explore the storytelling and instrumentation of country music.",
	"Study prehistoric life through fossils and geological evidence.",
	"Create textiles by interlacing threads on a loom.",
	"Learn about the formation and geology of volcanic mountains.",
	"Explore the philosophical and scientific questions of awareness.",
	"Master algorithms designed for quantum computers.",
	"Deepen your Go skills with advanced language features and techniques.",
	"Learn principles for designing systems that handle growth.",
	"Understand the patterns for building applications as small services.",
	"Explore concepts for building reliable systems across multiple machines.",
	"Develop Go applications optimized for cloud environments.",
	"Master techniques for managing concurrent operations in Go.",
	"Apply Go programming to data analysis and machine learning tasks.",
	"Build robust and efficient web applications using Go.",
	"Learn best practices for designing clear and effective Go APIs.",
	"Implement comprehensive testing strategies for Go codebases.",
}

var comments = []string{
	"Great post!",
	"Very informative, thanks for sharing.",
	"I learned something new today.",
	"Interesting perspective.",
	"Well written.",
	"Could you elaborate on this point?",
	"I have a question about...",
	"This is exactly what I was looking for.",
	"Helpful article.",
	"Thanks for the detailed explanation.",
	"I disagree with this part, but overall good.",
	"Looking forward to more content like this.",
	"Can you provide sources?",
	"This resonates with me.",
	"Excellent work!",
	"Simple and clear.",
	"Thought-provoking.",
	"I shared this with my colleagues.",
	"Bookmarked for later reading.",
	"Keep up the great work!",
	"This changed my perspective.",
	"Very practical advice.",
	"I appreciate the effort put into this.",
	"Nicely explained.",
	"This is gold.",
	"Mind blown!",
	"I never thought about it this way.",
	"Super helpful.",
	"Thanks for breaking it down.",
	"Concise and to the point.",
	"Love the examples.",
	"This is very relevant to my work.",
	"Inspiring!",
	"Well-researched.",
	"You've covered the topic thoroughly.",
	"I have a different experience with this.",
	"Could you do a follow-up post on...?",
	"This is a must-read.",
	"Brilliant!",
	"Saved me a lot of time.",
	"Perfect timing for this post.",
	"I found a small typo.",
	"The visuals are great.",
	"Easy to understand.",
	"This clarifies a lot.",
	"I'm implementing this right away.",
	"Valuable information.",
	"Thanks for the insights.",
	"This topic is fascinating.",
	"I wish I knew this earlier.",
	"Solid content.",
	"Makes perfect sense.",
	"I appreciate the clarity.",
	"This is quite comprehensive.",
	"Good points raised.",
	"I'll be referencing this often.",
	"Very engaging read.",
	"This answered my questions.",
	"Top-notch quality.",
	"I'm impressed.",
	"This is useful for beginners.",
	"Advanced users will appreciate this too.",
	"Well done!",
	"This is a complex topic, explained well.",
	"I like the structure of the post.",
	"The introduction hooked me.",
	"The conclusion summarizes it perfectly.",
	"Are there any alternatives to this approach?",
	"What are the potential drawbacks?",
	"This is a game-changer.",
	"I learned a lot.",
	"Thank you!",
	"Very well articulated.",
	"This deserves more attention.",
	"I'm glad I found this.",
	"This is very actionable.",
	"The examples are practical.",
	"I enjoyed reading this.",
	"This is a great resource.",
	"Kudos to the author.",
	"This is thought-provoking.",
	"I need to digest this.",
	"This aligns with my thoughts.",
	"I have a suggestion for improvement.",
	"This is incredibly detailed.",
	"I appreciate the honesty.",
	"This is refreshing.",
	"I'm sharing this on social media.",
	"This is exactly the information I needed.",
	"Very insightful.",
	"This post is packed with value.",
	"I admire the depth of knowledge.",
	"This is a fantastic overview.",
	"I'm looking forward to applying this.",
	"This is a cornerstone piece.",
	"Well-structured and logical.",
	"This is pure quality.",
	"I'm saving this for future reference.",
	"This is helpful for my project.",
	"Thank you for sharing your expertise.",
	"This is a clear explanation of a complex subject.",
	"I found this very motivating.",
}
var tags = []string{
	"Technology", "Programming", "Go", "Software Development", "Web Development",
	"Science", "Physics", "Astronomy", "Biology", "Neuroscience", "Genetics",
	"History", "Ancient Civilizations", "World History", "Art History", "Music History",
	"Art", "Painting", "Photography", "Design", "Writing", "Music", "Theater",
	"Nature", "Environment", "Climate Change", "Hiking", "Gardening", "Oceans",
	"Lifestyle", "Cooking", "Travel", "Meditation", "Health", "Finance", "Investing",
	"Business", "Marketing", "Entrepreneurship", "Economics", "Management",
	"Data Science", "Machine Learning", "AI", "Big Data", "Cloud Computing",
	"Cybersecurity", "Blockchain", "Networking", "DevOps", "Databases",
	"Education", "Learning", "Philosophy", "Psychology", "Sociology", "Culture",
	"Tutorial", "Guide", "Tips", "Best Practices", "Introduction", "Advanced",
	"Review", "Comparison", "Opinion", "Discussion", "News", "Update",
}

func Seed(store store.Storage , db *sql.DB) {
	ctx := context.Background()

	users := generateUsers(100)
	tx , err := db.BeginTx(ctx , nil)
	if err != nil {
		return
	}
	for _, user := range users {
		if err := store.Users.Create(ctx,tx ,user); err != nil {
			tx.Rollback()
			log.Println("Error creating users:", err)
			return
		}
	}
	tx.Commit()

	posts := generatePosts(200, users)

	for _, post := range posts {
		if err := store.Posts.Create(ctx, post); err != nil {
			log.Println("Error creating posts:", err)
			return
		}
	}

	comments := generateComments(600, users, posts)

	for _, comment := range comments {
		if err := store.Comments.Create(ctx, comment); err != nil {
			log.Println("Error creating comments : ", err)
			return
		}
	}
	log.Printf("Seeding Complete")

}
func generateUsers(num int) []*store.User {
	users := make([]*store.User, num)
	passwordText := "1234"
	pass := store.Password{
        Text: &passwordText,
        Hash: []byte{},
    }
	for i := 0; i < num; i++ {
		users[i] = &store.User{
			Username: userNames[i%len(userNames)] + fmt.Sprintf("%d", rand.Intn(5000)),
			Email:    userNames[i%len(userNames)] + fmt.Sprintf("%d", rand.Intn(5000)) + "@example.com",
			Password: pass,
		}
	}
	return users
}

func generatePosts(num int, users []*store.User) []*store.Post {
	posts := make([]*store.Post, num)

	for i := 0; i < num; i++ {
		user := users[rand.Intn(len(users))]

		posts[i] = &store.Post{
			UserID:  user.ID,
			Title:   titles[rand.Intn(len(titles))],
			Content: content[rand.Intn(len(content))],
			Tags: []string{
				tags[rand.Intn(len(tags))],
				tags[rand.Intn(len(tags))],
				tags[rand.Intn(len(tags))],
				tags[rand.Intn(len(tags))],
			},
		}
	}
	return posts
}

func generateComments(num int, users []*store.User, posts []*store.Post) []*store.Comment {
	cmt := make([]*store.Comment, num)

	for i := 0; i < num; i++ {
		cmt[i] = &store.Comment{
			PostID:  posts[rand.Intn(len(posts))].ID,
			UserID:  users[rand.Intn(len(users))].ID,
			Content: comments[rand.Intn(len(comments))],
		}

	}
	return cmt
}
